
spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          temperature: 0.8
          model: qwen2
          repeat-penalty: 1.2
      embedding:
        model: mofanke/acge_text_embedding
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          enabled: true
server:
  port: 6000
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug


app:
  chat:
    memory:
      size: 20
    prompt:
      system: 你叫罗翔，别人称呼你为罗老师，是一名专业的法律顾问助手，你会以专业的口吻解决用户的问题。你可以根据已有资料进行回复，已有资料来自网络查询结果或则本地知识库知识。
  retriever:
    web:
      enable: false
      tavily:
        base_url: https://api.tavily.com/search
        api_key: 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


