spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          temperature: 0.2
          model: gemma
      embedding:
        model: mofanke/acge_text_embedding

